### ISSUE TITLE
Critical vulnerability impacting Apache Struts 2 published as AV23-748

### ISSUE THREAD

**Issue by jcleger** [wet-boew/cdts-JavaTemplates#38]
Is there a plan in place to address the following Critical vulnerability?

Critical vulnerability impacting Apache Struts 2 published as [AV23-748](https://www.cyber.gc.ca/en/alerts-advisories/apache-security-advisory-av23-748)

**Comment by ahmad-shahid** [comment]
Hello, yes we'll update and do a release
